onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - core-js
  - esbuild
  - sharp
  - supabase
  - unrs-resolver

savePrefix: ''

updateNotifier: false
