import { Rajdhani } from 'next/font/google';
import './globals.css';

const rajdhani = Rajdhani({
  weight: ['500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-rajdhani',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface Props {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Props) {
  return (
    <html
      lang="en"
      className={`bg-dark-0 leading-normal text-light-0 ${rajdhani.variable}`}
    >
      <body>
        <div className="container flex flex-col gap-24 py-8 mobile:gap-40 tablet:py-40">
          {children}
        </div>
      </body>
    </html>
  );
}
