import { useLocale } from 'next-intl';
import { notFound } from 'next/navigation';

import Socials from '@/components/Socials';
import { Rajdhani } from 'next/font/google';
import Header from './components/Header';
import Hero from './components/Hero';

const rajdhani = Rajdhani({
  weight: ['500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-rajdhani',
});

export const dynamic = 'force-dynamic';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Local = 'en' | 'fa';

interface Props {
  children: React.ReactNode;
  params: { locale: Local };
}

export default function LocaleLayout({ children, params }: Props) {
  const locale = useLocale();

  if (params.locale !== locale) notFound();

  return (
    <html
      lang={locale}
      className={`bg-dark-0 leading-normal text-light-0 ${rajdhani.variable}`}
    >
      <body>
        <div className="container flex flex-col text-base gap-24 py-8 mobile:gap-40 tablet:py-40 w-full">
          <Header />
          <Hero />
          {children}
          <Socials />
        </div>
      </body>
    </html>
  );
}

export function generateStaticParams() {
  return [{ locale: 'en' }, { locale: 'fa' }];
}
